all: FindDevices getAllChanged getAll NewAddress setPeriod

FindDevices             :FindDevices.cpp ../iarduino_I2C_SHT.cpp
getAllChanged           :getAllChanged.cpp ../iarduino_I2C_SHT.cpp
getAll                  :getAll.cpp ../iarduino_I2C_SHT.cpp
NewAddress              :NewAddress.cpp ../iarduino_I2C_SHT.cpp
setPeriod               :setPeriod.cpp ../iarduino_I2C_SHT.cpp

clean:
	rm -f FindDevices getAllChanged getAll NewAddress setPeriod
